### ISSUE TITLE
fix for todomvc sample app

### ISSUE THREAD

**Issue by rubenmoor** [meiersi/blaze-react#17]
I think this his how the up-to-date `index.html` would look like:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>GHCJS • ReactJS • TodoMVC</title>
    <link rel="stylesheet" href="css/todomvc-common/base.css">
    <link rel="stylesheet" href="css/app.css">
    <script language="javascript" src="../dist/build/todomvc/todomvc.jsexe/rts.js"></script>
    <script language="javascript" src="../dist/build/todomvc/todomvc.jsexe/lib.js"></script>
    <script language="javascript" src="../dist/build/todomvc/todomvc.jsexe/out.js"></script>
  </head>
  <body>
  </body>
  <script language="javascript" src="runmain.js" defer></script>
</html>
```

**Comment by SimonMeierIBM** [comment]
Thanks for the input. What is the required change, and what is the reason for it?

**Comment by rubenmoor** [comment]
Two differences:

The current index.html contains the line:

    <script language="javascript" src="../dist/build/todomvc/todomvc.jsexe/lib1.js"></script>

However, `cabal configure -fbuild-example` does not create `lib1.js` and the sample app works perfectly without it.

Also the current index.html contains

```
 <script language="javascript">
    h$main(h$mainZCMainzimain);
  </script>
```

Which apparently has been replaced by `runmain.js`.

**Comment by SimonMeierIBM** [comment]
Ah I see. Thanks. What version of GHCJS are you using? Just to document it for posteriority.

PS: Out of curiosity, do you have concrete plans for using blaze-react? What are they, if you can say?

**Comment by asayers** [comment]
@meiersi: fyi, I already fixed this issue on the dev branch. Might be worth just cherry-picking the commit back to master. I can do it tonight.

**Comment by rubenmoor** [comment]
As far as I can see, there is only ghcjs 0.1.0.0. I am using current master branch and only just started to tag my code and select specific combinations of `ghcjs`, `blaze-react` and further libraries ... in an attempt to make the whole thing stable.

I am currently working on a haskell web framework with restful JSON api. GHCJS would be one nice way to implement the client for web browsers.
In detail the idea is, to create a haskell lib that is shared by browser and server and contains forms validation as digestive functors. That way forms and validation have to be defined only once.

Of course this only works with ghcjs. The whole package of ghcjs and blaze-react is incredibly powerful, in my opinion.

**Comment by SimonMeierIBM** [comment]
OK, cool. Thanks for the explanation. One thing you might consider is whether you're gonna need a only a RESTful API. Or put differently whether you should design for a RESTful API. A simple option is to base your framework on typesafe remote-procedure calls (RPCs) abstracted using GADTs as follows.

``` haskell
-- | A phantom-typed enumeration of all possible API calls supported by my-api.
data MyApi args result where
    LookupUser :: MyApi UserId (Maybe User)
    CreateUser :: MyApi User UserId
    ...

-- | Interpret an API call on a snap server (placed in a server-only module).
snapHandleMyApi :: MyApi args result -> args -> Snap result
snapHandleMyApi = 
    -- we probably just dispatch to to 'runMyApiIO' wrapped with exception handling
    -- and a function to render `results`s as HTTP responses.

-- | Another means of interpreting API's is to just run them as IO functions provided 
-- they get a handle to the database.
runMyApiIO :: Database.Handle -> MyApi args result -> args -> IO result
runMyApiIO = -- case distinction and custom DB calls for each function call

data ApiCall api = forall args result. ApiCall (api args result) args

instance ToJson (ApiCall MyApi) where
    toJson = -- tagged combination of toJson of the different args

myApiResultFromJson :: MyApi args result -> Aeson.Value -> Aeson.Parser result
myApiResultFromJson = -- caes dist on function and selection of fromJson parser

-- The key implementation of executing API calls on the client. See 
-- <https://www.fpcomplete.com/user/meiersi/the-service-pattern> for how to structure the
-- server handle code.
remoteMyApiCall :: Server.Handle -> MyApi args result -> args -> Async (Maybe result)
remoteMyApiCall serverH fun args = do
    asyncResult <- Server.jsonRPC serverH (toJson (ApiCall fun args))
    return $ Traversable.forM asyncResult $ \rawResult -> do
         case Aeson.eitherDecode (myApiResultFromJson fun) rawResult of
           Left err -> -- log error and return Nothing
           Right result -> return (Just result)
````

This way things like batching requests become obvious and you are by not limited to use exactly the RESTful vocabulary. You can as easily submit requests via JSON, zeromq, or whathever means you have available to call another service; i.e., whatever calling convention you can/want to use. In that context, REST really just becomes a calling convention for RPCs and an organization of related function calls.

Note also that different calling conventions have different failure modes. This is why the `MyApi` datatype only mentions the pure structure of the `result`. The `remoteMyApiCall` then tells you that you get asynchronous access to an optional result.

**Comment by asayers** [comment]
The commit I was referring to (6190965a) isn't cleanly cherry-pickable. I suggest we tidy up feat-async-apis and merge it into master.

**Comment by meiersi** [comment]
OK, I agree. Feel free to split off the experimental stuff and just merge
the polymorphic `req` type.

2015-03-12 14:28 GMT+01:00 Alex Sayers <notifications@github.com>:

**Comment by asayers** [comment]
It's probably going to break everyone's code, so I'm bumping the version number to blaze-react-0.2.

**Comment by asayers** [comment]
Closing as fixed.
