### ISSUE TITLE
Fixing dependencies

### ISSUE THREAD

**Issue by rubenmoor** [meiersi/blaze-react#19]
I ran into an issue when, from one day to another, my blaze-react client did not want to compile anymore. Cabal could not resolve the dependencies.

Since I have a lot of dependencies (e.g. digestive functors, and now even persist), there was no straightforward way for me, to figure out what *exactly* was the issue.

Now I have fixed it by pinning down the blaze-react dependency on `lens` by adding

    lens==4.7

to the `cabal.config` in blaze-react. (after I saw that lens had a very recent upgrade)

I'm lacking experience in issues like these. I'm glad I solved it and maybe someone else ran into the same issue. I guess I could try to pin my dependencies down in the `cabal.config` of my client, thereby limiting the options for blaze-react and preventing premature use of newer versions.

**Comment by meiersi** [comment]
In general, I think we should have reasonably precise dependencies in blaze-react. They are not there because the project is an a very experimental state. Feel free to send a pull request pinning down the major versions of the dependencies such that blaze-react compiles with GHC 7.8 and GHCJS 0.1.0.0

**Comment by asayers** [comment]
@rubenmoor: Would you be willing to help us test blaze-react 0.2 ahead of releasing it? The API has changed, so your code will need to be modified. You can find the code in the v0.2-rc1 branch.

**Comment by asayers** [comment]
The dependencies are already pinned down pretty well in the release candidate for blaze-react-0.2. Closing as fixed.
